import { jsPDF } from 'jspdf';
import type { ScanResult } from './types';

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function sanitizeHostname(url: string): string {
  try {
    return new URL(url).hostname.replace(/[^a-z0-9.-]/gi, '_');
  } catch {
    return 'scan';
  }
}

export function exportJson(result: ScanResult): void {
  const json = JSON.stringify(result, null, 2);
  const filename = `webshield-${sanitizeHostname(result.url)}-${Date.now()}.json`;
  downloadFile(json, filename, 'application/json');
}

function addHeader(doc: jsPDF, pageWidth: number) {
  doc.setFillColor(7, 24, 43);
  doc.rect(0, 0, pageWidth, 30, 'F');
  doc.setDrawColor(14, 165, 233);
  doc.setLineWidth(0.8);
  doc.roundedRect(15, 7, 16, 16, 3, 3, 'S');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text('Web', 37, 18);
  doc.setTextColor(14, 165, 233);
  doc.text('Shield', 49, 18);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(190, 205, 220);
  doc.text('WEBSITE SECURITY REPORT', pageWidth - 15, 18, { align: 'right' });
}

function addFooter(doc: jsPDF, pageWidth: number, pageHeight: number) {
  doc.setDrawColor(220, 226, 232);
  doc.setLineWidth(0.3);
  doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(105, 115, 125);
  doc.text('Generated by WebShield • webshield-zpv1.onrender.com', 15, pageHeight - 9);
  doc.text(`Page ${doc.getNumberOfPages()}`, pageWidth - 15, pageHeight - 9, { align: 'right' });
}

function ensureSpace(doc: jsPDF, y: number, needed: number, pageWidth: number, pageHeight: number): number {
  if (y + needed <= pageHeight - 22) return y;
  addFooter(doc, pageWidth, pageHeight);
  doc.addPage();
  addHeader(doc, pageWidth);
  return 40;
}

function sectionTitle(doc: jsPDF, title: string, y: number, pageWidth: number): number {
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(15, y, pageWidth - 30, 9, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(10, 55, 90);
  doc.text(title, 19, y + 6);
  return y + 14;
}

function addWrappedText(doc: jsPDF, text: string, x: number, y: number, width: number, fontSize = 8.5): number {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fontSize);
  doc.setTextColor(55, 65, 75);
  const lines = doc.splitTextToSize(String(text), width) as string[];
  doc.text(lines, x, y);
  return y + lines.length * (fontSize * 0.42);
}

export function exportPdfReport(result: ScanResult): void {
  const pageWidth = 210;
  const pageHeight = 297;
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
    encryption: {
      userPassword: '',
      ownerPassword: `webshield-${Date.now()}-${Math.random().toString(36).slice(2)}`,
      userPermissions: ['print'],
    },
  } as any);

  addHeader(doc, pageWidth);
  let y = 42;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);
  doc.text('Security Scan Report', 15, y);
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(90, 100, 110);
  doc.text(`Generated ${new Date(result.scannedAt).toLocaleString('en-US')}`, 15, y);
  y += 10;

  doc.setFillColor(247, 250, 252);
  doc.setDrawColor(220, 228, 235);
  doc.roundedRect(15, y, pageWidth - 30, 27, 3, 3, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(70, 80, 90);
  doc.text('SCANNED URL', 20, y + 8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(25, 35, 45);
  doc.text(doc.splitTextToSize(result.url, pageWidth - 50), 20, y + 14);
  if (result.finalUrl !== result.url) {
    doc.setFontSize(7.5);
    doc.setTextColor(95, 105, 115);
    doc.text(`Final URL: ${result.finalUrl}`, 20, y + 22);
  }
  y += 35;

  doc.setFillColor(7, 24, 43);
  doc.roundedRect(15, y, 55, 32, 3, 3, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(25);
  doc.setTextColor(14, 165, 233);
  doc.text(String(result.score), 24, y + 21);
  doc.setFontSize(9);
  doc.setTextColor(220, 235, 245);
  doc.text('/ 100', 47, y + 21);
  doc.setFontSize(9);
  doc.text(`Grade ${result.grade}`, 24, y + 27);

  doc.setFillColor(239, 250, 244);
  doc.setDrawColor(195, 230, 208);
  doc.roundedRect(76, y, pageWidth - 91, 32, 3, 3, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(20, 100, 55);
  doc.text(result.https.enabled ? 'HTTPS ENABLED' : 'HTTPS NOT ENABLED', 82, y + 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(55, 75, 65);
  doc.text(`HTTP redirect: ${result.https.redirectFromHttp ? 'Yes' : 'No'}`, 82, y + 17);
  doc.text(`TLS: ${result.https.protocol || 'Unknown'}`, 82, y + 23);
  doc.text(`Certificate valid: ${result.https.valid ? 'Yes' : 'No'}`, 82, y + 29);
  y += 42;

  y = sectionTitle(doc, 'Score Breakdown', y, pageWidth);
  if (result.scoreBreakdown) {
    const breakdown = [
      ['Transport (HTTPS/HSTS)', result.scoreBreakdown.transport],
      ['Content Security (CSP)', result.scoreBreakdown.content],
      ['Browser Security', result.scoreBreakdown.browser],
      ['Cookie Security', result.scoreBreakdown.cookies],
      ['Infrastructure', result.scoreBreakdown.infrastructure],
    ];
    for (const [label, value] of breakdown) {
      y = ensureSpace(doc, y, 8, pageWidth, pageHeight);
      doc.setFontSize(8.5);
      doc.setTextColor(55, 65, 75);
      doc.text(String(label), 18, y);
      doc.text(Number(value).toFixed(1), pageWidth - 18, y, { align: 'right' });
      doc.setFillColor(225, 232, 238);
      doc.roundedRect(18, y + 2, pageWidth - 36, 2.5, 1, 1, 'F');
      doc.setFillColor(14, 165, 233);
      doc.roundedRect(18, y + 2, Math.max(0, Math.min(1, Number(value) / 40)) * (pageWidth - 36), 2.5, 1, 1, 'F');
      y += 10;
    }
  }
  y += 4;

  y = sectionTitle(doc, 'HTTPS & Certificate', y, pageWidth);
  const httpsRows = [
    ['HTTPS Enabled', result.https.enabled ? 'Yes' : 'No'],
    ['HTTP → HTTPS Redirect', result.https.redirectFromHttp ? 'Yes' : 'No'],
    ['HSTS Preload Ready', result.https.hstsPreloadReady ? 'Yes' : 'No'],
    ['Protocol', result.https.protocol || 'Unknown'],
    ['Certificate Issuer', result.https.issuer || 'Unknown'],
    ['Certificate Expires', result.https.expiresAt || 'Unknown'],
    ['Days Remaining', result.https.daysRemaining > 0 ? String(result.https.daysRemaining) : '0'],
  ];
  for (const [label, value] of httpsRows) {
    y = ensureSpace(doc, y, 7, pageWidth, pageHeight);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(70, 80, 90);
    doc.text(label, 18, y);
    y = addWrappedText(doc, value, 65, y, pageWidth - 83, 8);
    y += 3;
  }

  y += 2;
  y = sectionTitle(doc, 'Server Information', y, pageWidth);
  const serverRows = [
    ['Server', result.server.server || 'Hidden'],
    ['X-Powered-By', result.server.xPoweredBy || 'Hidden'],
    ['Compression', result.server.compression || 'None'],
    ['Final Status', `HTTP ${result.server.finalStatusCode}`],
    ['Redirects', String(result.server.redirectCount)],
  ];
  for (const [label, value] of serverRows) {
    y = ensureSpace(doc, y, 7, pageWidth, pageHeight);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(70, 80, 90);
    doc.text(label, 18, y);
    y = addWrappedText(doc, value, 65, y, pageWidth - 83, 8);
    y += 3;
  }

  y += 2;
  y = sectionTitle(doc, `Security Headers (${result.headers.length})`, y, pageWidth);
  for (const header of result.headers) {
    y = ensureSpace(doc, y, 18, pageWidth, pageHeight);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.2);
    doc.setTextColor(30, 40, 50);
    doc.text(header.name, 18, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(header.status === 'present' ? 20 : 180, header.status === 'present' ? 110 : 70, 70);
    doc.text(header.status.toUpperCase(), pageWidth - 18, y, { align: 'right' });
    y += 4;
    y = addWrappedText(doc, `Value: ${header.value || 'Not set'}`, 18, y, pageWidth - 36, 7.5);
    y += 3;
  }

  y += 2;
  y = sectionTitle(doc, 'Vulnerability Summary', y, pageWidth);
  const vuln = result.vulnerabilities;
  y = addWrappedText(doc, `Total: ${vuln.count}   Critical: ${vuln.critical}   High: ${vuln.high}   Medium: ${vuln.medium}   Low: ${vuln.low}   Info: ${vuln.info}`, 18, y, pageWidth - 36, 8.5);
  y += 8;

  y = ensureSpace(doc, y, 12, pageWidth, pageHeight);
  y = sectionTitle(doc, `Recommendations (${result.recommendations.length})`, y, pageWidth);
  for (const rec of result.recommendations) {
    y = ensureSpace(doc, y, 25, pageWidth, pageHeight);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(30, 40, 50);
    doc.text(`[${rec.severity.toUpperCase()}] ${rec.title}`, 18, y);
    y += 5;
    y = addWrappedText(doc, rec.description, 18, y, pageWidth - 36, 7.8);
    y += 2;
    y = addWrappedText(doc, `Example: ${rec.exampleImplementation}`, 18, y, pageWidth - 36, 7.4);
    y += 5;
  }

  y = ensureSpace(doc, y, 20, pageWidth, pageHeight);
  y = sectionTitle(doc, 'Raw Response Headers', y, pageWidth);
  for (const header of result.rawHeaders) {
    y = ensureSpace(doc, y, 8, pageWidth, pageHeight);
    y = addWrappedText(doc, `${header.name}: ${header.value}`, 18, y, pageWidth - 36, 7.2);
    y += 2;
  }

  addFooter(doc, pageWidth, pageHeight);
  const filename = `webshield-${sanitizeHostname(result.url)}-${Date.now()}.pdf`;
  doc.save(filename);
}

export function copyResults(result: ScanResult): Promise<void> {
  const text = formatResultsForSharing(result);
  return navigator.clipboard.writeText(text);
}

export function formatResultsForSharing(result: ScanResult): string {
  const lines: string[] = [];
  lines.push('WebShield Security Scan Results');
  lines.push('');
  lines.push(`URL: ${result.url}`);
  if (result.finalUrl !== result.url) {
    lines.push(`Final URL: ${result.finalUrl}`);
  }
  lines.push(`Score: ${result.score}/100 (Grade: ${result.grade})`);
  lines.push(`HTTPS: ${result.https.enabled ? 'Enabled' : 'Not Enabled'}`);
  lines.push(`HTTP Redirect: ${result.https.redirectFromHttp ? 'Yes' : 'No'}`);
  lines.push(`Headers: ${result.headers.filter((h) => h.status === 'present').length}/${result.headers.length} present`);
  lines.push(`Vulnerabilities: ${result.vulnerabilities.count} (${result.vulnerabilities.critical} critical, ${result.vulnerabilities.high} high, ${result.vulnerabilities.medium} medium, ${result.vulnerabilities.low} low, ${result.vulnerabilities.info} info)`);
  if (result.cookies.length > 0) {
    const insecure = result.cookies.filter((c) => c.weaknesses.length > 0).length;
    lines.push(`Cookies: ${result.cookies.length} (${insecure} with weaknesses)`);
  }
  lines.push('');
  if (result.recommendations.length > 0) {
    lines.push('Top Recommendations:');
    for (const rec of result.recommendations.slice(0, 3)) {
      lines.push(`  - [${rec.severity}] ${rec.title}`);
    }
  }
  lines.push('');
  lines.push('Scanned with WebShield — https://webshield-zpv1.onrender.com');
  return lines.join('\n');
}

export async function shareResults(result: ScanResult): Promise<boolean> {
  const text = formatResultsForSharing(result);
  if (navigator.share) {
    try {
      await navigator.share({
        title: 'WebShield Security Scan',
        text,
      });
      return true;
    } catch {
      return false;
    }
  }
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
